# Generated by Django 4.1.4 on 2022-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
